name: arduino k210 release based on ESP32 Arduino Release

on:
  release:
    types: published

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Build Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./tools/on-release.sh
